import { Injectable, signal } from '@angular/core';
import { IProduct } from '../interfaces/iproduct';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
    private _products = signal<IProduct[]>([
    {
      id: 1,
      name: "Laptop Pro 15",
      price: 2300,
      category: "Laptops",
      description: "High-performance laptop for development and video editing.",
      image: "https://picsum.photos/seed/laptop1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 2,
      name: "Smartphone Max 12",
      price: 999,
      category: "Mobile Phones",
      description: "Flagship smartphone with 6.7-inch OLED display and 120Hz refresh rate.",
      image: "https://picsum.photos/seed/phone1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 3,
      name: "Wireless Headphones X2",
      price: 199,
      category: "Audio",
      description: "Noise-cancelling over-ear headphones with 30-hour battery life.",
      image: "https://picsum.photos/seed/headphones1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 4,
      name: "Mechanical Keyboard K7",
      price: 149,
      category: "Accessories",
      description: "RGB backlit keyboard with tactile switches and programmable keys.",
      image: "https://picsum.photos/seed/keyboard1/400/400",
      inStock: false,
      addedAt: new Date().toISOString(),
    },
    {
      id: 5,
      name: "Gaming Mouse Pro",
      price: 79,
      category: "Accessories",
      description: "Ergonomic mouse with high-precision optical sensor and RGB lighting.",
      image: "https://picsum.photos/seed/mouse1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 6,
      name: "4K Ultra Monitor 27\"",
      price: 450,
      category: "Monitors",
      description: "27-inch 4K UHD monitor ideal for graphic design and gaming.",
      image: "https://picsum.photos/seed/monitor1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 7,
      name: "Smartwatch Active S3",
      price: 179,
      category: "Wearables",
      description: "Track workouts, heart rate, and sleep with this sleek smartwatch.",
      image: "https://picsum.photos/seed/watch1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 8,
      name: "Tablet Air 11",
      price: 520,
      category: "Tablets",
      description: "Lightweight tablet perfect for browsing, note-taking, and streaming.",
      image: "https://picsum.photos/seed/tablet1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 9,
      name: "Portable SSD 1TB",
      price: 140,
      category: "Storage",
      description: "Compact, high-speed external SSD for fast backups.",
      image: "https://picsum.photos/seed/ssd1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 10,
      name: "Bluetooth Speaker Mini",
      price: 59,
      category: "Audio",
      description: "Portable wireless speaker with rich bass and 12-hour battery life.",
      image: "https://picsum.photos/seed/speaker1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 11,
      name: "Noise-Free Microphone Pro",
      price: 129,
      category: "Accessories",
      description: "USB microphone for podcasts, streaming, and meetings.",
      image: "https://picsum.photos/seed/mic1/400/400",
      inStock: false,
      addedAt: new Date().toISOString(),
    },
    {
      id: 12,
      name: "Laptop Stand Aluminum",
      price: 49,
      category: "Accessories",
      description: "Ergonomic aluminum laptop stand with adjustable height.",
      image: "https://picsum.photos/seed/laptop2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 13,
      name: "Smartphone Mini 11",
      price: 699,
      category: "Mobile Phones",
      description: "Compact smartphone with powerful performance and great camera.",
      image: "https://picsum.photos/seed/phone2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 14,
      name: "Gaming Headset RGB",
      price: 89,
      category: "Audio",
      description: "Over-ear gaming headset with surround sound and RGB lighting.",
      image: "https://picsum.photos/seed/headphones2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 15,
      name: "Graphics Tablet Pro",
      price: 250,
      category: "Accessories",
      description: "Professional drawing tablet with pressure-sensitive stylus.",
      image: "https://picsum.photos/seed/tablet2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 16,
      name: "Smart Glasses AR",
      price: 599,
      category: "Wearables",
      description: "Augmented reality glasses for notifications and media viewing.",
      image: "https://picsum.photos/seed/glasses1/400/400",
      inStock: false,
      addedAt: new Date().toISOString(),
    },
    {
      id: 17,
      name: "USB-C Docking Station",
      price: 89,
      category: "Accessories",
      description: "Expand your laptop with USB ports, HDMI, and Ethernet connections.",
      image: "https://picsum.photos/seed/dock1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 18,
      name: "Wireless Charger Pad",
      price: 35,
      category: "Accessories",
      description: "Fast wireless charger compatible with all Qi-enabled devices.",
      image: "https://picsum.photos/seed/charger1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 19,
      name: "Laptop Pro 13",
      price: 2100,
      category: "Laptops",
      description: "Lightweight 13-inch laptop perfect for travel and work.",
      image: "https://picsum.photos/seed/laptop3/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 20,
      name: "Tablet Mini 8",
      price: 320,
      category: "Tablets",
      description: "Compact tablet great for kids or casual use.",
      image: "https://picsum.photos/seed/tablet3/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 21,
      name: "Gaming Laptop GX",
      price: 2800,
      category: "Laptops",
      description: "High-end gaming laptop with RTX graphics and high-refresh display.",
      image: "https://picsum.photos/seed/laptop4/400/400",
      inStock: false,
      addedAt: new Date().toISOString(),
    },
    {
      id: 22,
      name: "Smartphone Ultra 13",
      price: 1100,
      category: "Mobile Phones",
      description: "Premium smartphone with triple-camera setup and long battery life.",
      image: "https://picsum.photos/seed/phone3/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 23,
      name: "Bluetooth Earbuds S",
      price: 59,
      category: "Audio",
      description: "Compact wireless earbuds with noise isolation and long battery life.",
      image: "https://picsum.photos/seed/earbuds1/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 24,
      name: "Mechanical Keyboard Mini",
      price: 99,
      category: "Accessories",
      description: "Compact 60% keyboard for gamers and programmers.",
      image: "https://picsum.photos/seed/keyboard2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    },
    {
      id: 25,
      name: "Smartwatch Lite",
      price: 129,
      category: "Wearables",
      description: "Affordable smartwatch for fitness tracking and notifications.",
      image: "https://picsum.photos/seed/watch2/400/400",
      inStock: true,
      addedAt: new Date().toISOString(),
    }
  ]);

  products = this._products.asReadonly();

  getProductById(id: number) {
    return this.products().find(p => p.id === id);
  }

  updateProduct(updated: IProduct) {
    this._products.update(list =>
      list.map(p => p.id === updated.id ? updated : p)
    );
  }
}
